# Generated by Django 2.2.1 on 2020-05-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-publish',)},
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='published',
            new_name='publish',
        ),
    ]
